version: '3.7'

services:
  messagingservice.api:
    image: ${DOCKER_REGISTRY-}messagingserviceapi
    depends_on:
      - "messagingservice.mongo_db"
    build:
      context: .
      dockerfile: MessagingService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  messagingservice.mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/MongoDb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - "messagingservice.mongo_db"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: messagingservice.mongo_db
      ME_CONFIG_MONGODB_PORT: 27017